apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "jumia-phone-validator.fullname" . }}
  labels:
    app: {{ include "jumia-phone-validator.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "jumia-phone-validator.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "jumia-phone-validator.name" . }}
    spec:
      containers:
        - name: backend
          image: "{{ .Values.image.repositoryBackend }}:{{ .Values.image.tagBackend }}"
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://{{ .Values.rds_endpoint }}/{{ .Values.db_name }}"
            - name: SPRING_DATASOURCE_USERNAME
              value: "{{ .Values.db_user }}"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "{{ .Values.db_password }}"
        - name: frontend
          image: "{{ .Values.image.repositoryFrontend }}:{{ .Values.image.tagFrontend }}"
          ports:
            - containerPort: 8081
