apiVersion: v1
kind: Service
metadata:
  name: jumia-phone-validator
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: jumia-phone-validator
