---
- name: Setup PostgreSQL Database Content
  hosts: microservice
  become: yes
  gather_facts: no
  vars_files:
    - ../group_vars/all.yml

  tasks:
    - name: Install PostgreSQL client tools
      apt:
        name: postgresql-client
        state: present
        update_cache: yes

    - name: Create temporary directory for SQL file
      file:
        path: /tmp/sql_import
        state: directory
        mode: '0755'

    - name: Copy sample SQL file from repository to temp location
      copy:
        src: "{{ app_source_dir }}/jumia_phone_validator/database/sample.sql"
        dest: /tmp/sql_import/sample.sql
        mode: '0644'
        remote_src: yes

    - name: Dump sample.sql into the RDS database
      become: no
      shell: >
        PGPASSWORD="{{ db_password }}" psql -h {{ rds_endpoint }} -U {{ db_username }} -d {{ db_name }} -f /tmp/sql_import/sample.sql
      environment:
        PGPASSWORD: "{{ db_password }}"
      register: psql_output
      changed_when: "'ERROR' not in psql_output.stderr"
      failed_when: "'FATAL' in psql_output.stderr or 'ERROR' in psql_output.stderr"

    - name: Clean up temporary SQL file and directory
      file:
        path: /tmp/sql_import
        state: absent
