pipeline {
    agent any
    environment {
        AWS_REGION    = "eu-central-1"
        ECR_REGISTRY  = "992122884453.dkr.ecr.eu-central-1.amazonaws.com"
        FRONTEND_IMAGE= "validator-frontend"
        BACKEND_IMAGE = "validator-backend"
        HELM_RELEASE  = "jumia-phone-validator"
        HELM_CHART_DIR= "k8s/helm-chart"
    }
    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }
        stage('Build Docker Images') {
            steps {
                script {
                    sh 'docker-compose -f k8s/docker-compose.yml build'
                    sh 'docker-compose -f k8s/docker-compose.yml push'
                }
            }
        }
        stage('Deploy to EKS with Helm') {
            steps {
                script {
                    sh 'aws eks update-kubeconfig --region $AWS_REGION --name ${HELM_RELEASE}-eks'
                    sh """
                       helm upgrade --install ${HELM_RELEASE} ${HELM_CHART_DIR} \\
                         --set image.repositoryBackend=${ECR_REGISTRY}/${BACKEND_IMAGE} \\
                         --set image.repositoryFrontend=${ECR_REGISTRY}/${FRONTEND_IMAGE}
                    """
                }
            }
        }
    }
    post {
        success {
            echo 'Deployment successful!'
        }
        failure {
            echo 'Deployment failed.'
        }
    }
}
