replicaCount: 3

image:
  repositoryBackend: "992122884453.dkr.ecr.eu-central-1.amazonaws.com/validator-backend"
  tagBackend: "latest"
  repositoryFrontend: "992122884453.dkr.ecr.eu-central-1.amazonaws.com/validator-frontend"
  tagFrontend: "latest"

service:
  type: ClusterIP
  port: 80

#DB connection settings
rds_endpoint: "jumia-sre-challenge-db.ceg9ua9ljrsl.eu-central-1.rds.amazonaws.com:5432"
db_name: "jumia_phone_validator"
db_user: "jumia"
db_password: "Cherotich12!"  

ingress:
  enabled: false

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
